### ISSUE TITLE
Address epistemology

### ISSUE THREAD

**Issue by amyjko** [amyjko/foundations-of-information#10]
Epistemology is central to defining knowledge, but the knowledge chapter only briefly mentions it and it doesn't come up anywhere else in the book. Think about how to engage it and where.

**Comment by orcmid** [comment]
(having not read the Knowledge chapter yet).

I always feel lost when "epistemology" comes up.  I remember stumbling on it in some writing by John McCarthy.

My sense of it is that epistemology is not so much about what we know but rather, how we know.  Which I suppose would be a pertinent question for an AI "knowing" anything.  Hoping for something down-to-earth, I just found the definition as the "investigation of what distinguishes justified belief from opinion."  Reminds me of Clifford's "The Ethics of Belief," something rather pertinent in today's world.  Off to read the Knowledge chapter.
