### ISSUE TITLE
Cite cyberbullying survey

### ISSUE THREAD

**Issue by amyjko** [amyjko/foundations-of-information#18]
https://dl.acm.org/doi/abs/10.1145/3424246

This has a nice collection of techniques for detecting and a discussion of their limitations.

**Comment by orcmid** [comment]
Wow, that is very dense.  

((Side weirdness: The DOI abstract entry says January 2021, the entry for Vol.54 No.1 says April 2021, and the document itself says December 2020 as the publication date.  I can't even ... authoritative source indeed.))
