### ISSUE TITLE
Date incorrect in Chapter 1 The power of information

### ISSUE THREAD

**Issue by takib-beep** [amyjko/foundations-of-information#19]
Aloha,

You write, "In February and March 2019, an international community of American and Chinese researchers worked together to model, describe, and share the structure of the SARS-CoV-2 spike." which I ought to be February and March 2020.  SARS-CoV-2 hadn't yet been identified in early 2019.

Thank you for writing this entire "book."

**Comment by amyjko** [comment]
Thank you for reporting!
