### ISSUE TITLE
Incoherent passage, Chapter 1

### ISSUE THREAD

**Issue by cschris71** [amyjko/foundations-of-information#25]
Third to last paragraph: "But the power of information, therefore, derives more from its meaning, its context, and how it is received and used, and less from how it is transmitted or received." "Received" is used here for opposite cases, and "received and used" sounds almost the same as "transmitted or received."  You seem to be talking about the difference between meaning/function and technology, but it's not at all clear what these terms designate and whether you are simply making the same point as below (challenging "the medium is the message").

**Comment by amyjko** [comment]
Thanks for the feedback! I've improved this.

**Comment by cschris71** [comment]
Glad to help! I really enjoy the textbook so far, it's great and I imagine
sorely needed. Hope it's OK to leave other suggestions if I find any.
Best, Chris

**Comment by amyjko** [comment]
Absolutely, please share any and all thoughts. Thanks!
