### ISSUE TITLE
minor edits: "it's" ch 1 + 3

### ISSUE THREAD

**Issue by RhoBott** [amyjko/foundations-of-information#28]
Both bolded below (emphasis mine) should be sans apostrophe

ch1
> Throughout, we shall see that while information is powerful in **it’s** capacity to shape action, and information technology can make it even more powerful, information can also be perilous to capture and share without doing great harm and injustice.

ch3
> From a process perspective, the door itself is not information, but particular people in particular situations may glean different information from the door and **it’s** relation to other social context about its meaning.

**Comment by amyjko** [comment]
Thanks!
