### ISSUE TITLE
suggestion: seminal -> foundational (or etc.)

### ISSUE THREAD

**Issue by RhoBott** [amyjko/foundations-of-information#30]
Perhaps consider "foundational" (or formative, important, key, vital, central, earth-moving, game-changing, ground-breaking [or other noun-gerund combinations] ... ) instead of _seminal_? 

Four appearances in text:
ch 3
> In his **seminal** work, he linked information to the concept of entropy from thermodynamics.

ch 4
> This history of analog encodings directly informed the digital encodings that followed Shannon’s **seminal** work on information theory.

ch 9
> What determines when information management becomes necessary? The answer to this question goes back to some **seminal** work from Herb Simon, who said in (yet another) **seminal** work, Designing Organizations for an Information-rich World

**Comment by amyjko** [comment]
Ah, interesting, is this a feminist critique of the word's etymology? Or just a redundancy critique?

**Comment by RhoBott** [comment]
Reasonable question, apologies for not being clearer. The former.

**Comment by amyjko** [comment]
Great, thanks! I hadn't encountered that critique before, but now that I see it, it seems like a word well worth avoiding. Edits on their way.
