### ISSUE TITLE
Typo in Chapter 12

### ISSUE THREAD

**Issue by JakeC007** [amyjko/foundations-of-information#47]
I think there is a typo in the following sentence. I have bolded the issue.

"many researchers are **investing** new forms of decentralized moderation, such as online harassment moderation systems that use friends instead of platform maintainers or moderators."

I'm enjoying the book! Thank you for writing it

**Comment by JakeC007** [comment]
Additionally, this sentence is confusing. I think I get what you're saying but I am not quite sure what's going on with the text I have bolded. 

"Distance work, for example, really only succeeds when groups have high common ground, loosely coupled work with few dependencies, and a strong commitment for both collaboration and collaboration technologies **succeed**, reducing the need for communication, collaboration, and coordination21."

**Comment by amyjko** [comment]
Thanks for reporting! Fixed.
