### ISSUE TITLE
Chapter 16 Typos

### ISSUE THREAD

**Issue by JakeC007** [amyjko/foundations-of-information#49]
Missing a space

"no organized role in society, since there is no **society.Such** a system maximizes"

Consider changing how you mention Pres #45 
"on January 8th, 2021, Twitter permanently suspended the account of President Trump after he incited mob violence on the U.S. capital."

According to this [source](https://emilypost.com/advice/addressing-a-former-president-of-the-united-states) former President [last name] or Mr. [last name] are both acceptable. I've seen most venues do both. Obviously, this is a stylistic change and kinda nitpicky but I figured I would bring it up anyway.

**Comment by amyjko** [comment]
Thanks for pointing out the issue with the title. It is a surprisingly tricky and subtle stylistic choice!
