### ISSUE TITLE
License Clash?

### ISSUE THREAD

**Issue by orcmid** [amyjko/foundations-of-information#5]
I notice you are using CC0 on the repository, a quit-claim to sort-of force the work into the public domain.  For those who want to rely on copies/adaptations of the material, some might want to establish the provenance of such work.  I wonder how that would best be done.  Do you have a suggested way?

My original reason for this issue though, is to note that the CC0 quit claim is different than the CC-By-No-Derivatives that appears at https://faculty.washington.edu/ajko/books/foundations-of-information/#/

**Comment by amyjko** [comment]
Thanks for catching that, it was stale default from I first created the repo.
