### ISSUE TITLE
Interoperability

### ISSUE THREAD

**Issue by JakeC007** [amyjko/foundations-of-information#52]
In Chapter 15 you mention data interoperability. I think its an interesting topic that is worth a definfition (i.e., you define many other terms that are more common, like capitalism). I would also argue that a small aside on data interoperability is worthwhile. Perhaps in the context of how many of our current information systems came to be by leveraging interoperability and then slamming the door behind them with prickly EULAS noninmally backed by Computer Fraud and Abuse Act. Cory Doctorow has written a bit about adversarial interoperability recently which may prove to be a good citation if you want to add this stuff to your book.   

* https://www.eff.org/deeplinks/2019/10/adversarial-interoperability

* https://www.ycombinator.com/library/6c-cory-doctorow-on-adversarial-interoperability

**Comment by amyjko** [comment]
Thanks for the suggestions! I agree, it could be an interesting addition.
