### ISSUE TITLE
Typo in the Hiding Chapter

### ISSUE THREAD

**Issue by EddieNew** [amyjko/foundations-of-information#85]
In the Hiding chapter, there is a sentence that says "One modern form of privacy invasion online is doxxing, a complex form of online harassment that involves seeking private or personally identifying information about someone and widely distributing it through mass media without consent, typically with subtle or sometimes explicit calls to harm toe person."
The second to last word should be "to a" not "toe".

**Comment by amyjko** [comment]
Thank you Edward!
