### ISSUE TITLE
Ada Lovelace Omission in Chapter 5

### ISSUE THREAD

**Issue by KrishnaBhat00** [amyjko/foundations-of-information#91]
In the Chapter 5 subsection 'Computing Emerges,' the book goes through a brief history of the computer, from Charles Babbage's mind to the the Apple II Macintosh. You explain several important people and their practical and theoretical innovations and end with this: 

> (If you’re wondering why all of these inventors were White men, look no further than the 20th century universities in the United States and United Kingdom, which [systematically excluded women and people of color](https://www.cam.ac.uk/TheRisingTide) until the 1960’s. Universities are where most of this invention occurred, and where all of the world’s computers were, as computers took up entire rooms rooms in which women, Black, Asian, Hispanic, and Native people simply weren’t allowed).

While I don't disagree that the history of the computer was dominated by White men, nor that the explicit discrimination of women and people of color in US/UK universities is the main motivating factor. But I find it that you left out a very prominent woman in history: Ada Lovelace. 
Lovelace is sometimes credited with the first 'computer program' (I believe this may be disputed), but also with the first conceptualization of Babbage's ideas being used for non-mathematical uses, nearly 100 years before Bush did.  
I admit that my knowledge on the subject is relatively sparse, but she was always included in every history of computers I have heard, which is why I was surprised to see her missing. 
With the best intentions, 
Krishna

**Comment by orcmid** [comment]
There are some good bibliographic sources on Ada Lovelace, including one by Harry Huskey and his wife.  What's important to recognize is that Ada was highly privileged.  August De Morgan tutored her.  This was not a collegiate experience at all.  I don't recall exactly how she became associated with Babbage, but it was definitely what we would call non-traditional.  The Babbage Analytical Engine, which was a programmable device, was mechanical and, as I recall, never completed.  So computing had not yet emerged.  See https://en.wikipedia.org/wiki/Analytical_engine.   That does not diminish Lovelace's achievement.  It just isn't on a tight progression to what computing is recognized as today.  And remarkable nonetheless.

**Comment by amyjko** [comment]
Thanks @KrishnaBhat00, good catch! Lovelace would be good to add, especially since Babbage is already mentioned, and she was his protégé.

In a different book I authored (which is much longer than this one), there's a much more thorough treatment of history (an entire chapter):

https://criticallyconsciouscomputing.org/history

But there's enough detail in Chapter 5 to justify mentioning her, and her role in conceiving of algorithms.

I'll add this edit to my backlog.
