### ISSUE TITLE
Missing word or confusing sentence

### ISSUE THREAD

**Issue by mxwe** [amyjko/foundations-of-information#92]
Near the end of Chapter 14: Information + Automation, you write, "The truth is that we have always had to make challenging moral, ethical, and sociopolitical choices what power we give people, and what power we give technology, and how that power of information technology is used to enrich our lives, or abused to subjugate or oppress."

I'm having a hard time making sense of this complex idea. Flagging it for review.

**Comment by amyjko** [comment]
Thanks for reporting. I'll publish a revision in a bit.
